# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'search_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtGui import *


class Ui_Dialog(QDialog):
    def __init__(self):
        super().__init__()
        self.setupUi()

    def setupUi(self):
        self.resize(540, 485)
        self.horizontalLayoutWidget = QWidget()
        self.horizontalLayoutWidget.setGeometry(QRect(40, 30, 151, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.label = QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.label.setText("단지코드 ")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)

        self.toolButton = QToolButton()
        self.toolButton.setGeometry(QRect(470, 40, 27, 31))
        self.toolButton.setObjectName("toolButton")

        self.tableWidget = QTableWidget()
        self.tableWidget.setGeometry(QRect(40, 100, 471, 321))
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QTableWidgetItem()

        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText("단지코드")
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText("단지명")

        self.retranslateUi()

        self.buttonBox = QDialogButtonBox()
        self.buttonBox.setGeometry(QRect(170, 430, 341, 32))
        self.buttonBox.setOrientation(Qt.Horizontal)
        self.buttonBox.setStandardButtons(QDialogButtonBox.Cancel|QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.buttonBox.accepted.connect(self.accept) # type: ignore
        self.buttonBox.rejected.connect(self.reject) # type: ignore
        # QMetaObject.connectSlotsByName(self)

    def accept(self):
        print("fagsd")

    def retranslateUi(self):
        _translate = QCoreApplication.translate
        # Dialog.setWindowTitle(_translate("Dialog", "Dialog"))

        # self.toolButton.setText(_translate("Dialog", "..."))



if __name__ == "__main__":
    app = QApplication(sys.argv)
    # Dialog = QDialog()
    ui = Ui_Dialog()
    # ui.setupUi()
    ui.show()
    # sys.exit(app.exec_())
